# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: keygen-service-account
#   annotations:
#     "helm.sh/hook": pre-install
#     "helm.sh/hook-weight": "-5"

# ---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: keygen-role
#   annotations:
#     "helm.sh/hook": pre-install
#     "helm.sh/hook-weight": "-5"
# rules:
#   - apiGroups: [""]
#     resources: ["configmaps"]
#     verbs: ["get", "create", "delete", "update"]

# ---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: keygen-rolebinding
#   annotations:
#     "helm.sh/hook": pre-install
#     "helm.sh/hook-weight": "-5"
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: keygen-role
# subjects:
#   - kind: ServiceAccount
#     name: keygen-service-account
