apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-keys-config-map
data:
  private-key.pem: |-
{{ .Files.Get "files/microservices/auth/keys/jwt_private.pem" | nindent 4 }}
  public-key.pem: |-
{{ .Files.Get "files/microservices/auth/keys/jwt_public.pem" | nindent 4 }}